### ISSUE TITLE
segy_loader failing to broadcast input array shape during conversion

### ISSUE THREAD

**Issue by Tdarnell** [trhallam/segysak#110] opened 2022-07-18 11:47 UTC
Platform: Anaconda 3.8.12, windows 10
Segysak version: 0.3.4

I am encountering this error on some of my 2D sub-bottom profiler SEGY files whilst trying to load with segysak. It seems to depend on the orientation on the acquired segy files, as alternating files load fine. 

```
ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_8748/2613756.py in <module>
     36 
     37 # use the segysak segy_loader to load the 2D segy file
---> 38 sgy = segy_loader(segy_path, vert_domain="TWT", cdp=9, cdpx=73, cdpy=77, offset=109)

c:\Users\\\\\lib\site-packages\segysak\segy\_segy_loader.py in segy_loader(segyfile, cdp, iline, xline, cdpx, cdpy, offset, vert_domain, data_type, ix_crop, cdp_crop, xy_crop, z_crop, return_geometry, silent, extra_byte_fields, head_df, **segyio_kwargs)
   1170     elif head_loc.cdp is not None:
   1171         print("Loading as 2D")
-> 1172         ds = _2dsegy_loader(*common_args, **common_kwargs, **segyio_kwargs)
   1173         indexer = ["cdp_index"]
   1174         dims = (

c:\Users\\\\\lib\site-packages\segysak\segy\_segy_loader.py in _2dsegy_loader(segyfile, head_df, head_bin, head_loc, ncfile, vert_domain, data_type, crop, zcrop, silent, return_geometry, **segyio_kwargs)
    680     # # prestack data
    681     if head_loc.offset is not None:
--> 682         ds = _segy2d_ps_xr(
    683             segyfile,
    684             ds,

c:\Users\\\\\lib\site-packages\segysak\segy\_segy_loader.py in _segy2d_ps_xr(segyfile, ds, segyio_kwargs, n0, ns, head_df, head_loc, vert_domain, silent)
    567         # this can probably be done as a block - leaving for now just incase sorting becomes an issue
...
--> 569             volume[int(val.cdp_index), :, int(val.off_index)] = segyf.trace[trc][
    570                 n0 : ns + 1
    571             ]

ValueError: could not broadcast input array from shape (1958,) into shape (1959,)
```

**Comment by trhallam** [comment] 2022-07-18 13:11
It looks like there is an error in the size of the xarray calculated and the number of traces in your file.

Can I ask if the CDPs are numbered backwards in the bad file?

**Comment by Tdarnell** [comment] 2022-07-18 13:51
> It looks like there is an error in the size of the xarray calculated and the number of traces in your file.
> 
> Can I ask if the CDPs are numbered backwards in the bad file?

The CDP's are not numbered backwards, in this file they start at 7724 and end at 8641, I unfortunately can't share the files as an example of this issue. They are out of sync by 1 with the trace sequence numbers if that matters? (byte 1-4, I tried using these bytes as the CDP and it made no difference).

**Comment by trhallam** [comment] 2022-07-18 14:07
Ok, another issue might be if you have duplicate offset values in your data, or if your data contain pilot traces, which are not part of the geometry. 

If you load all the header data using `segy_header_scrape` you can look for problems with the header information and correct these before loading.

The last thing you can do is try to load the data just as 2D, without broadcasting into orthogonal dimensions (e.g. cdp/offset). Then examine the data to discover the issue. You can simply do this by changing the offset keyword to `offset_check` or similar so segysak doesn't try to do anything except load the traces as 2D. 

You can then broadcast after the fact by reindexing along the `offset_check` variable, and this might give you more information about the cause of the error.

**Comment by trhallam** [comment] 2023-02-23 18:22
Closing due to inactivity.

**Closed by trhallam** 2023-02-23 18:22 UTC
